name: GIOL Research Group
url: http://iol.etsii.upm.es/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: staff
    name: Staff
  - key: postdoc
    name: Researchers
  - key: grad
    name: Students
  - key: ugrad
    name: Undergraduate Students
  - key: ugrad-alum
    name: Past Undergraduate Students
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  #- title: People
    #link: /#people
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Google Scholar
    url: https://scholar.google.com/citations?view_op=list_works&hl=en&user=IrNpshUAAAAJ&gmla=AJsN-F45sc61YZHuPnNvMXGAuyzwhVVBGGM-44oD-PeTsUXUUWjNkssy9u9g4u2U2kqhqQ2pfmhM2v_SKrFF-5aGj3H4LUn_IriM89pwSOVwJj-sYjKABZQ
  #- title: Code
  #  link: /code.html
